on: [push, pull_request]

jobs:
  bundle:
    name: Bundle ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install briefcase setuptools
      - name: Make Bundle
        shell: bash
        run: |
          pwd
          ls -la
          briefcase create
          briefcase build
          if [ "$RUNNER_OS" == "macOS" ]; then
                briefcase package --no-sign
          else
                briefcase package
          fi
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v1
        with:
          name: napari_installer
          path: ${{ github.workspace }}${{ ( runner.os == 'Windows' && '/windows/*.msi' ) || ( runner.os == 'Linux' && '/linux/*.AppImage' ) || ( runner.os == 'macOS' && '/macOS/*.dmg' ) }}

