on: [push, pull_request]


jobs:
  bundle:
    name: Bundle ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-16.04, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install briefcase
      - name: Patch Briefcase
        if: runner.os == 'macOS'
        run: python patch_briefcase.py
      - name: Make nix Bundle
        if: runner.os != 'Windows'
        env:
          output: ${{ ( runner.os == 'macOS' && './macOS/*.dmg' ) || './linux/*.AppImage' }}
          cmd: ${{ ( runner.os == 'macOS' && 'briefcase package --no-sign' ) || 'briefcase package' }}
          DMGSIZE: '1.4g'
        run: |
          briefcase create
          briefcase build
          mkdir -p ${{ github.workspace }}/artifact
          ${{ env.cmd }}
          mv ${{ env.output }} ${{ github.workspace }}/artifact
      - name: Make Windows Bundle
        if: runner.os == 'Windows'
        run: |
          briefcase create
          briefcase build
          mkdir -p artifact
          briefcase package
          move windows\*.msi artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: napari_installer-${{ runner.os }}-${{ github.sha }}
          path: artifact/

